# Generated by Django 4.1 on 2022-08-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSrv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videosrv_name', models.CharField(max_length=30, verbose_name='Название')),
                ('videosrv_addr', models.CharField(max_length=15, verbose_name='Адрес')),
                ('videosrv_https', models.IntegerField(null=True, verbose_name='Порт HTTPS')),
                ('videosrv_http', models.IntegerField(null=True, verbose_name='Порт HTTP')),
                ('videosrv_user', models.CharField(max_length=15, verbose_name='Пользователь')),
                ('videosrv_password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Видео сервер',
                'verbose_name_plural': 'Видео серверы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameras_name', models.CharField(max_length=30, verbose_name='Название')),
                ('cameras_channel', models.CharField(max_length=8, verbose_name='Id канала')),
                ('cameras_srv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras_srv', to='trassir.videosrv', verbose_name='Видеосервер')),
            ],
            options={
                'verbose_name': 'Камеру',
                'verbose_name_plural': 'Камеры',
                'ordering': ['pk'],
            },
        ),
    ]
