# Generated by Django 4.1 on 2022-08-06 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trassir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyBoard',
            fields=[
                ('key_name', models.CharField(default='BtnX-', max_length=10, primary_key=True, serialize=False, verbose_name='Id')),
                ('key_rus', models.CharField(max_length=20, verbose_name='Рус')),
                ('key_eng', models.CharField(max_length=20, verbose_name='Англ')),
                ('key_rele1', models.IntegerField(null=True, verbose_name='Реле 1')),
                ('key_rele2', models.IntegerField(null=True, verbose_name='Реле 2')),
                ('key_class', models.CharField(max_length=30, null=True, verbose_name='Класс')),
                ('key_option1', models.CharField(max_length=10, null=True, verbose_name='Опция 1')),
                ('key_option2', models.CharField(max_length=10, null=True, verbose_name='Опция 2')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Клавиатура',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Pumps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(max_length=30, verbose_name='Название')),
                ('pump_addr', models.CharField(max_length=15, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Насос',
                'verbose_name_plural': 'Насосы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=30, verbose_name='Название')),
                ('system_key', models.CharField(max_length=15, verbose_name='Адрес клавиатуры')),
                ('system_contr', models.CharField(max_length=15, verbose_name='Адрес контроллера')),
                ('system_perc', models.FloatField(verbose_name='Скорость')),
                ('system_depth', models.FloatField(verbose_name='Глубина')),
                ('system_pumpint', models.IntegerField(verbose_name='Вход задвижки насоса')),
                ('system_pumpvalve', models.IntegerField(verbose_name='Реле задвижки насоса')),
                ('system_pumprele1', models.IntegerField(verbose_name='Реле1 насоса')),
                ('system_pumprele2', models.IntegerField(default=0, verbose_name='Реле2 насоса')),
                ('system_duet', models.IntegerField(default=0, verbose_name='Связка')),
                ('system_camera', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='trassir.cameras', verbose_name='Камера')),
                ('system_pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump', to='valley.pumps', verbose_name='Контроллер насоса')),
            ],
            options={
                'verbose_name': 'Систему полива',
                'verbose_name_plural': 'Системы полива',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('states_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='valley.systems', verbose_name='Система')),
                ('states_ctrl', models.BooleanField(default=False, verbose_name='Управление')),
                ('states_fail', models.BooleanField(default=False, verbose_name='Авария')),
                ('states_dir', models.CharField(choices=[('N', '-'), ('F', 'Вперёд'), ('R', 'Назад')], default='N', max_length=1, verbose_name='Направление')),
                ('states_wat', models.BooleanField(default=False, verbose_name='Вода')),
                ('states_sis', models.BooleanField(default=False, verbose_name='АвтоСтоп')),
                ('states_valve1', models.BooleanField(default=False, verbose_name='Задвижка 1')),
                ('states_valve2', models.BooleanField(default=False, verbose_name='Задвижка 2')),
                ('status_perc', models.FloatField(verbose_name='Скорость')),
                ('status_depth', models.FloatField(verbose_name='Глубина')),
                ('status_time', models.DateTimeField(verbose_name='Время запуска')),
            ],
            options={
                'verbose_name': 'Состояние системы',
                'verbose_name_plural': 'Состояния систем',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('C', 'Управление'), ('M', 'Мониторинг')], default='C', max_length=1, verbose_name='Роль')),
                ('user_lang', models.CharField(choices=[('R', 'RUS'), ('E', 'ENG')], default='R', max_length=1, verbose_name='Язык клавиатуры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('journal_user', models.CharField(default='admin', max_length=20, verbose_name='Пользователь')),
                ('journal_act', models.CharField(choices=[('R', 'Запуск'), ('S', 'Остановка')], default='S', max_length=1, verbose_name='Действия')),
                ('journal_dir', models.CharField(choices=[('N', '-'), ('F', 'Вперёд'), ('R', 'Назад')], default='N', max_length=1, verbose_name='Направление')),
                ('journal_wat', models.BooleanField(default=False, verbose_name='Вода')),
                ('journal_sis', models.BooleanField(default=False, verbose_name='АвтоСтоп')),
                ('journal_fail', models.BooleanField(default=False, verbose_name='Авария')),
                ('journal_perc', models.FloatField(verbose_name='Скорость')),
                ('journal_depth', models.FloatField(verbose_name='Глубина')),
                ('journal_hours', models.FloatField(verbose_name='Время')),
                ('journal_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valley.systems', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Журнал',
            },
        ),
    ]
