# Generated by Django 4.1 on 2022-08-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
